### ISSUE TITLE
Integration with an Existing MVC Core 2.1 Application

### ISSUE THREAD

**Issue by webzest** [PiranhaCMS/piranha.core.examples#2]
Great work on building Piranha.  I just started learning .NET Core and already developed several applications that I am using for my Photography Business.  Here is my Web Sites:  https://www.webzest.com and https://www.johnnysandaire.com.  
I am excited to learn how to use Piranha to add a dedicated blog to JohnnySandaire.com.
How can I integrate Piranha with JohnnySandaire.com as /blog with archive lists, like this https://blog.JohnnySandaire.com

**Comment by tidyui** [comment]
Hi again. I created this repository as an example of how to just add blogging features from Piranha into an existing .NET Core MVC application. Go through the example and look at it, if you have any specific questions you **need** to specify exactly **what** you're having an issue with, otherwise I can't help you. The current question is to general and unspecified.

Best regards

Håkan
